services:
  done:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - done-data:/data
    environment:
      - TZ=UTC
    restart: unless-stopped

volumes:
  done-data:
    driver: local
